### ISSUE TITLE
recommend other packages to install to build test with success

### ISSUE THREAD

**Issue by omac777** [hermit-os/hermit-gcc#5]
```
sudo apt-get install clang-tools-11
sudo pip3 install lit
```

**Comment by omac777** [comment]
Also I believe the tools should be explicitly using python3 since python2 has been deprecated.

**Comment by mkroening** [comment]
Sorry for not following up earlier. We've reworked the toolchain setup. Please look at the new `README.md`. If this issue persists, please reopen. :)
